name: JSC System Docker Images Quick Test

on:
  push:
    paths:
      - 'jsc-system/**'
      - '.github/workflows/jsc-system-image-quick-test.yml'


jobs:
  quick-test:
    runs-on: ubuntu-18.04

    strategy:
      fail-fast: false
      matrix:
        arch: ['arm32', 'mips32el']

    container: pmatos/jsc-qemu-system-${{ matrix.arch }}:latest

    steps:
      - name: Checkout WebKit-misc
        uses: actions/checkout@v2
      - name: Checkout WebKit
        run: git clone --depth=1 -j $(nproc) https://github.com/WebKit/WebKit /WebKit
      - name: Build
        run: jsc-system/build-jsc.sh --release /WebKit /buildroot
      - name: Test
        run: jsc-system/test-jsc.sh --release --vms 3 --port 60000 --timeout 1800 --filter '^stress/regress-.*' /WebKit /buildroot
