name: Shellcheck JSC QEMU System

on:
  pull_request:
    paths:
      - 'jsc-system/**'
      - '.github/workflows/shellcheck-jsc-qemu-system.yml'
  push:
    paths:
      - 'jsc-system/**'
      - '.github/workflows/shellcheck-jsc-qemu-system.yml'

jobs:
  check:
    runs-on: ubuntu-latest
    container: debian:buster-slim

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get Shellcheck
        run: apt-get update && apt-get install -y shellcheck
      - name: Check
        working-directory: ./jsc-system
        run: shellcheck -x *.sh

