name: Build JSC32

on: push
      
jobs:
  build:    
    runs-on: ubuntu-18.04

    strategy:
      fail-fast: false
      matrix:
        arch: [arm32, mips32el]
        unified: [ON, OFF]
        static: [ON, OFF]

    container: pmatos/jsc-qemu-system-${{ matrix.arch }}
          
    steps:
      - name: Checkout WebKit
        run: git clone --depth=1 https://git.webkit.org/git/WebKit-https.git WebKit
      - name: Build
        working-directory: ./WebKit
        run: Tools/Scripts/build-jsc --ra --jsc-only --cmakeargs="-DCMAKE_TOOLCHAIN_FILE=/buildroot/share/buildroot/toolchainfile.cmake -DENABLE_STATIC_JSC=${{ matrix.static }} -DENABLE_UNIFIED_BUILDS=${{ matrix.unified }}"
      
