name: Build JSC32

on:
  push:
    paths:
      - '.github/workflows/webkit-build.yml'
  schedule:
    - cron: '0 */4 * * *'
      
jobs:
  build-i386:
    runs-on: ubuntu-18.04
    container: pmatos/jsc-x86_32

    strategy:
      fail-fast: false
      matrix:
        unified: [unified, no-unified]
        static: [static, no-static]
        mode: [ra, debug, release]

    steps:
      - name: Checkout WebKit
        run: git clone --depth=1 https://github.com/webkit/webkit /webkit
      - name: Checking revision
        working-directory: /webkit
        run: git log --oneline -n1 HEAD
      - name: Set static
        if: matrix.static == 'static'
        run: echo "static=ON" >> $GITHUB_ENV
      - name: Set no-static
        if: matrix.static == 'no-static'
        run: echo "static=OFF" >> $GITHUB_ENV
      - name: Set unified
        if: matrix.unified == 'unified'
        run: echo "unified=ON" >> $GITHUB_ENV
      - name: Set no-unified
        if: matrix.unified == 'no-unified'
        run: echo "unified=OFF" >> $GITHUB_ENV
      - name: Build
        working-directory: /webkit
        run: Tools/Scripts/build-jsc --32-bit --${{ matrix.mode }} --jsc-only --cmakeargs="-DENABLE_STATIC_JSC=${static} -DENABLE_UNIFIED_BUILDS=${unified}"
  
  build-cross32bits:
    runs-on: ubuntu-18.04

    strategy:
      fail-fast: false
      matrix:
        arch: [arm32, mips32el]
        unified: [unified, no-unified]
        static: [static, no-static]
        mode: [ra, debug, release]

    container: pmatos/jsc-qemu-system-${{ matrix.arch }}
          
    steps:
      - name: Install git and deps
        run: |
          apt-get update
          apt-get install -y build-essential git curl openssl
      - name: Checkout WebKit
        run: git clone --depth=1 https://github.com/webkit/webkit /webkit
      - name: Checking revision
        working-directory: /webkit
        run: git log --oneline -n1 HEAD
      - name: Set static
        if: matrix.static == 'static'
        run: echo "static=ON" >> $GITHUB_ENV
      - name: Set no-static
        if: matrix.static == 'no-static'
        run: echo "static=OFF" >> $GITHUB_ENV
      - name: Set unified
        if: matrix.unified == 'unified'
        run: echo "unified=ON" >> $GITHUB_ENV
      - name: Set no-unified
        if: matrix.unified == 'no-unified'
        run: echo "unified=OFF" >> $GITHUB_ENV
      - name: Build
        working-directory: /webkit
        run: Tools/Scripts/build-jsc --${{ matrix.mode }} --jsc-only --cmakeargs="-DCMAKE_TOOLCHAIN_FILE=/buildroot/share/buildroot/toolchainfile.cmake -DENABLE_STATIC_JSC=${static} -DENABLE_UNIFIED_BUILDS=${unified}"
      
  build-64bits:
    runs-on: ubuntu-18.04

    strategy:
      fail-fast: false
      matrix:
        unified: [unified, no-unified]
        static: [static, no-static]
        mode: [ra, debug, release]

    container: ubuntu:20.04

    env:
      DEBIAN_FRONTEND: noninteractive
    
    steps:
      - name: Install git and deps
        run: |
          apt-get update
          apt-get install -y build-essential git curl openssl cmake python perl ruby libicu-dev
      - name: Set timezone
        run: ln -fs /usr/share/zoneinfo/Europe/Berlin /etc/localtime
      - name: Checkout WebKit
        run: git clone --depth=1 https://github.com/webkit/webkit /webkit
      - name: Checking revision
        working-directory: /webkit
        run: git log --oneline -n1 HEAD
      - name: Set static
        if: matrix.static == 'static'
        run: echo "static=ON" >> $GITHUB_ENV
      - name: Set no-static
        if: matrix.static == 'no-static'
        run: echo "static=OFF" >> $GITHUB_ENV
      - name: Set unified
        if: matrix.unified == 'unified'
        run: echo "unified=ON" >> $GITHUB_ENV
      - name: Set no-unified
        if: matrix.unified == 'no-unified'
        run: echo "unified=OFF" >> $GITHUB_ENV
      - name: Build
        working-directory: /webkit
        run: Tools/Scripts/build-jsc --${{ matrix.mode }} --jsc-only --cmakeargs="-DENABLE_STATIC_JSC=${static} -DENABLE_UNIFIED_BUILDS=${unified}"
      
